export interface AIResponse {
  content: string;
  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
  cost: number;
  model: string;
}

export class MockAIService {
  static async generatePurchaseOrder(data: {
    selectedVendor: any;
    items: any[];
    deliveryDetails: any;
    terms: any;
  }): Promise<AIResponse> {
    // Simulate processing time
    await new Promise(resolve => setTimeout(resolve, 1000));

    const content = `
# Purchase Order Generated Successfully

## Vendor Information
- **Name**: ${data.selectedVendor.name}
- **Contact**: ${data.selectedVendor.contact?.email || 'N/A'}

## Items Ordered
${data.items.map(item => `
- **${item.sku}**: ${item.description}
  - Quantity: ${item.quantity}
  - Unit Price: $${item.unitPrice}
  - Total: $${item.quantity * item.unitPrice}
`).join('')}

## Delivery Details
- **Required Date**: ${data.deliveryDetails.requiredDate}
- **Shipping Method**: ${data.deliveryDetails.shippingMethod}

## Terms and Conditions
- **Payment Terms**: ${data.terms.paymentTerms}
- **Quality Standards**: ${data.terms.qualityStandards || 'Standard'}
- **Warranty**: ${data.terms.warrantyRequirements || 'Standard'}

## AI Recommendations
1. **Cost Optimization**: Consider bulk ordering for better pricing
2. **Delivery**: Expedited shipping recommended for urgent items
3. **Quality**: Vendor has excellent quality ratings
4. **Risk**: Low risk supplier with proven track record

*This purchase order was generated by AI and should be reviewed before submission.*
    `;

    return {
      content: content.trim(),
      usage: {
        prompt_tokens: 150,
        completion_tokens: 300,
        total_tokens: 450
      },
      cost: 0.001,
      model: 'mock-ai'
    };
  }

  static async evaluateVendors(data: {
    vendors: any[];
    requirements: any;
    evaluationCriteria: any;
  }): Promise<AIResponse> {
    await new Promise(resolve => setTimeout(resolve, 1500));

    const content = `
# Vendor Evaluation Report

## Evaluation Summary
Analyzed ${data.vendors.length} vendors based on your requirements.

## Vendor Comparison Matrix

${data.vendors.map((vendor, index) => `
### ${index + 1}. ${vendor.name}
- **Overall Score**: ${vendor.qualityRating}/100
- **Cost Rating**: ${vendor.costRating}/100
- **Delivery Performance**: ${vendor.deliveryPerformance}/100
- **Location**: ${vendor.location}
- **Payment Terms**: ${vendor.paymentTerms}
- **Minimum Order**: $${vendor.minimumOrder || 'N/A'}

**Strengths**: High quality ratings, good delivery performance
**Considerations**: ${vendor.costRating < 80 ? 'Cost optimization needed' : 'Competitive pricing'}
`).join('')}

## Recommendations
1. **Top Choice**: ${data.vendors[0]?.name || 'Vendor 1'} - Best overall value
2. **Cost Leader**: ${data.vendors.find(v => v.costRating > 85)?.name || 'Vendor 2'} - Best pricing
3. **Quality Leader**: ${data.vendors.find(v => v.qualityRating > 90)?.name || 'Vendor 1'} - Best quality

## Risk Assessment
- **Low Risk**: All vendors have good track records
- **Medium Risk**: Consider backup suppliers for critical items
- **High Risk**: None identified

*This evaluation was generated by AI and should be used as a guide for decision making.*
    `;

    return {
      content: content.trim(),
      usage: {
        prompt_tokens: 200,
        completion_tokens: 400,
        total_tokens: 600
      },
      cost: 0.002,
      model: 'mock-ai'
    };
  }

  static async optimizeCosts(data: {
    currentSpend: any;
    vendorContracts: any[];
    marketData: any;
    constraints: any;
  }): Promise<AIResponse> {
    await new Promise(resolve => setTimeout(resolve, 2000));

    const totalSpend = Object.values(data.currentSpend).reduce((sum: number, val: any) => sum + Number(val), 0);
    const potentialSavings = totalSpend * 0.15; // 15% savings potential

    const content = `
# Cost Optimization Analysis

## Current Spend Overview
- **Total Annual Spend**: $${totalSpend.toLocaleString()}
- **Categories**: ${Object.keys(data.currentSpend).length} categories analyzed
- **Vendor Contracts**: ${data.vendorContracts.length} active contracts

## Optimization Opportunities

### 1. Volume Consolidation
- **Potential Savings**: $${(potentialSavings * 0.4).toLocaleString()}
- **Strategy**: Consolidate orders across departments
- **Implementation**: 3-6 months

### 2. Vendor Negotiation
- **Potential Savings**: $${(potentialSavings * 0.3).toLocaleString()}
- **Strategy**: Renegotiate existing contracts
- **Implementation**: 2-4 months

### 3. Alternative Sourcing
- **Potential Savings**: $${(potentialSavings * 0.2).toLocaleString()}
- **Strategy**: Identify new suppliers
- **Implementation**: 4-8 months

### 4. Process Optimization
- **Potential Savings**: $${(potentialSavings * 0.1).toLocaleString()}
- **Strategy**: Streamline procurement processes
- **Implementation**: 1-3 months

## Total Potential Savings
**$${potentialSavings.toLocaleString()}** (15% of current spend)

## Implementation Roadmap
1. **Month 1-2**: Volume consolidation analysis
2. **Month 3-4**: Vendor negotiations
3. **Month 5-6**: Alternative sourcing evaluation
4. **Month 7-8**: Process optimization implementation

## Risk Mitigation
- Maintain quality standards during transitions
- Ensure supplier diversity for critical items
- Monitor performance metrics throughout implementation

*This analysis was generated by AI and should be validated with procurement experts.*
    `;

    return {
      content: content.trim(),
      usage: {
        prompt_tokens: 250,
        completion_tokens: 500,
        total_tokens: 750
      },
      cost: 0.003,
      model: 'mock-ai'
    };
  }

  static async generateGeneralResponse(prompt: string): Promise<AIResponse> {
    await new Promise(resolve => setTimeout(resolve, 800));

    const content = `
# AI Analysis Response

## Summary
This is a mock AI response for development and testing purposes.

## Analysis
Based on the provided data, here are the key insights:

1. **Data Processing**: Successfully analyzed the input parameters
2. **Pattern Recognition**: Identified relevant patterns and trends
3. **Recommendations**: Generated actionable recommendations
4. **Risk Assessment**: Evaluated potential risks and opportunities

## Next Steps
1. Review the analysis with stakeholders
2. Implement recommended actions
3. Monitor results and adjust strategies
4. Document lessons learned

*This is a mock response for development purposes. In production, this would be replaced with actual AI analysis.*
    `;

    return {
      content: content.trim(),
      usage: {
        prompt_tokens: 100,
        completion_tokens: 200,
        total_tokens: 300
      },
      cost: 0.001,
      model: 'mock-ai'
    };
  }
} 