import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export class TMSService {
  /**
   * Automatically builds a shipment for a given order.
   * In a real system, this would group multiple orders.
   * @param orderId The ID of the allocated order.
   */
  static async autoBuildShipment(orderId: string) {
    console.log(`Building Shipment for Order: ${orderId}`);

    // 1. Fetch Order
    const order = await prisma.order.findUnique({
      where: { id: orderId },
      include: {
        orderItems: { include: { item: true } },
        customer: true
      }
    });

    if (!order) throw new Error(`Order ${orderId} not found`);
    if (order.status !== 'ALLOCATED') {
      console.warn(`Order ${orderId} is not ALLOCATED (Status: ${order.status}). Skipping shipment build.`);
      return null;
    }

    // 2. Create Shipment Header
    const shipmentNumber = `SHP-${order.orderNumber}`;
    const shipment = await prisma.shipment.create({
      data: {
        organizationId: order.organizationId,
        shipmentNumber: shipmentNumber,
        status: 'PLANNED',
        mode: 'LTL', // Default
        totalWeight: 0, // Should calculate
        totalVolume: 0, // Should calculate
        metadata: {
          autoGenerated: true,
          sourceOrderId: orderId
        }
      }
    });

    // 3. Create Shipment Pieces (from Order Items)
    for (const item of order.orderItems) {
      await prisma.shipmentPiece.create({
        data: {
          shipmentId: shipment.id,
          orderId: order.id,
          orderItemId: item.id,
          sku: item.item.sku,
          quantity: item.quantity,
          weight: item.item.unitWeightKG ? Number(item.item.unitWeightKG) * item.quantity : 0,
          description: item.item.productName
        }
      });
    }

    // 4. Update Order Status
    await prisma.order.update({
      where: { id: order.id },
      data: { status: 'PLANNED' }
    });

    console.log(`Shipment ${shipmentNumber} created for Order ${order.orderNumber}`);
    return shipment;
  }
}
